import Foundation

/// A remembered channel. `sourceId` is kept so a row can say where it came from.
public struct IptvHistoryItem: Codable, Hashable, Identifiable {
    public let sourceId: String
    public let title: String
    public let url: String
    public let type: IptvEntryType
    public let kind: IptvKind
    public let timestamp: Date
    /// Replaying has to reach the same destination as the first play, and a YouTube page handed to
    /// the player would only fail there.
    public let playback: IptvPlayback
    /// Kept so a remembered row looks like the row it was played from.
    public let logo: String

    /// Keyed by address, like the Android store: the same channel reached from two sources is one
    /// favourite, and a catalog reload that renumbers entry ids leaves favourites intact.
    public var id: String { url }

    public init(
        sourceId: String,
        title: String,
        url: String,
        type: IptvEntryType,
        kind: IptvKind,
        timestamp: Date = Date(),
        playback: IptvPlayback = .stream,
        logo: String = ""
    ) {
        self.sourceId = sourceId
        self.title = title
        self.url = url
        self.type = type
        self.kind = kind
        self.timestamp = timestamp
        self.playback = playback
        self.logo = logo
    }

    /// The item as something the player and the queue can take, so a remembered row replays without
    /// reloading the portal catalog — which is the slow step on large Xtream accounts.
    public var asEntry: IptvEntry {
        IptvEntry(
            id: url,
            title: title,
            categoryId: IptvCatalogData.allCategoryId,
            type: type,
            url: url,
            logo: logo,
            playback: playback
        )
    }
}

/// Recently played and favourited IPTV entries.
///
/// The playable URL is stored alongside the title so a recent item replays without reloading the
/// whole portal catalog. Those URLs are credentials — an Xtream stream URL carries the account's
/// username and password in its own path — so this is written through `SecretStore` exactly like
/// `IptvSourceStore`, rather than being treated as ordinary history.
/// Mirrors the Android `IptvHistoryStore`.
@MainActor
public final class IptvHistoryStore: ObservableObject {
    @Published public private(set) var favorites: [IptvHistoryItem] = []
    @Published public private(set) var recent: [IptvHistoryItem] = []

    private static let maxRecent = 30

    private let service: String
    private let favoritesAccount = "favorites"
    private let recentAccount = "recent"
    private let defaults: UserDefaults
    private let legacyKeys = ["iptv.favorites.v1", "iptv.recent.v1"]

    public init(defaults: UserDefaults = .standard, service: String = "dev.autobridge.iptv.history") {
        self.defaults = defaults
        self.service = service
        // An earlier build kept both lists in UserDefaults as plain `IptvEntry` values. The shape
        // changed with the move to URL-keyed items, so the plaintext copy is dropped rather than
        // migrated: history is regenerated by using the app, and a stale favourite is not worth
        // leaving a readable copy of a credentialed URL behind for.
        legacyKeys.forEach { defaults.removeObject(forKey: $0) }
        favorites = decode(favoritesAccount)
        recent = decode(recentAccount)
    }

    public func recent(kind: IptvKind) -> [IptvHistoryItem] {
        recent.filter { $0.kind == kind }
    }

    public func favorites(kind: IptvKind) -> [IptvHistoryItem] {
        favorites.filter { $0.kind == kind }
    }

    public func isFavorite(url: String) -> Bool {
        favorites.contains { $0.url == url }
    }

    public func recordPlayback(source: IptvSource, entry: IptvEntry) {
        recordPlayback(item(from: entry, source: source))
    }

    public func recordPlayback(_ item: IptvHistoryItem) {
        guard !item.url.isEmpty else { return }
        recent.removeAll { $0.url == item.url }
        recent.insert(item, at: 0)
        if recent.count > Self.maxRecent {
            recent = Array(recent.prefix(Self.maxRecent))
        }
        encode(recent, recentAccount)
    }

    /// Adds or removes `entry` from favourites. Returns true when it is a favourite afterwards.
    @discardableResult
    public func toggleFavorite(source: IptvSource, entry: IptvEntry) -> Bool {
        toggleFavorite(item(from: entry, source: source))
    }

    /// The same toggle, for the surfaces that hold a remembered item rather than a catalog entry —
    /// the player, the Favorites list and the CarPlay now-playing screen.
    @discardableResult
    public func toggleFavorite(_ item: IptvHistoryItem) -> Bool {
        guard !item.url.isEmpty else { return false }
        if let index = favorites.firstIndex(where: { $0.url == item.url }) {
            favorites.remove(at: index)
            encode(favorites, favoritesAccount)
            return false
        }
        favorites.append(item)
        encode(favorites, favoritesAccount)
        return true
    }

    public func removeFavorite(url: String) {
        favorites.removeAll { $0.url == url }
        encode(favorites, favoritesAccount)
    }

    public func clearRecent() {
        recent = []
        encode(recent, recentAccount)
    }

    public func clearFavorites() {
        favorites = []
        encode(favorites, favoritesAccount)
    }

    private func item(from entry: IptvEntry, source: IptvSource) -> IptvHistoryItem {
        IptvHistoryItem(
            sourceId: source.id,
            title: entry.title,
            url: entry.url,
            type: entry.type,
            kind: source.kind,
            playback: entry.playback,
            logo: entry.logo
        )
    }

    private func decode(_ account: String) -> [IptvHistoryItem] {
        let raw = SecretStore.read(service: service, account: account)
        guard !raw.isEmpty, let data = raw.data(using: .utf8),
              let decoded = try? JSONDecoder().decode([IptvHistoryItem].self, from: data) else {
            return []
        }
        return decoded
    }

    private func encode(_ items: [IptvHistoryItem], _ account: String) {
        guard let data = try? JSONEncoder().encode(items),
              let text = String(data: data, encoding: .utf8) else { return }
        SecretStore.write(service: service, account: account, value: text)
    }
}
